## server
#server:
#  port: 8080
#
spring:
  autoconfigure.exclude: org.keycloak.adapters.springboot.KeycloakSpringBootConfiguration
  data.web.pageable:
    default-page-size: 20
    max-page-size: 100
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
    schema: classpath*:/db/h2/bootstrap_schema.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      show_sql: false
    show-sql: false

keycloak:
  realm: puff
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: course-management
  principal-attribute: preferred_username
  bearer-only: true

swagger:
  auth:
    token-url: test
    client-id: test
    client-secret: test
  api:
    title: Course Management REST Api
    description: Course Management REST Api documentation and management
    contact:
      name: Benjamin Kostiuk
      url:
      email: benkostiuk1@gmail.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
    version: 0.0.1